"""Initial watchlist, carried over 1:1 from the existing Tiingo monitor."""

TICKERS = {
    "ABBV": "AbbVie",
    "ADDYY": "Adidas",
    "AMD": "Advanced Micro Devices",
    "GOOGL": "Alphabet (Google)",
    "BABA": "Alibaba Group",
    "AAL": "American Airlines",
    "AXP": "American Express",
    "AMZN": "Amazon",
    "AMC": "AMC Entertainment",
    "AAPL": "Apple",
    "ASML": "ASML Holding",
    "TBB": "AT&T",
    "ACB": "Aurora Cannabis",
    "BAC-P-E": "Bank of America",
    "BAYZF": "Bayer",
    "BRK-A": "Berkshire Hathaway",
    "BA": "Boeing",
    "BP": "BP (British Petroleum)",
    "AVGO": "Broadcom",
    "CGC": "Canopy Growth",
    "CCL": "Carnival Corporation",
    "CAT": "Caterpillar",
    "SAVA": "Cassava Sciences",
    "CVX": "Chevron",
    "CMG": "Chipotle Mexican Grill",
    "CSCO": "Cisco Systems",
    "KO": "Coca-Cola",
    "COIN": "Coinbase Global",
    "COST": "Costco Wholesale",
    "DELL": "Dell Technologies",
    "DRSHF": "Droneshield",
    "XOM": "ExxonMobil",
    "FDX": "FedEx",
    "FI": "Fiserv",
    "GME": "GameStop",
    "GE": "General Electric",
    "GSBD": "Goldman Sachs",
    "HON": "Honeywell International",
    "HD": "Home Depot",
    "IBM": "IBM",
    "INTC": "Intel",
    "JNJ": "Johnson & Johnson",
    "DLAKY": "Lufthansa Group",
    "LVMHF": "LVMH",
    "MA": "Mastercard",
    "MCD": "McDonald's",
    "MPW": "Medical Properties Trust",
    "MRK": "Merck & Co.",
    "META": "Meta",
    "B4B.HM": "Metro AG",
    "STRK": "MicroStrategy",
    "MSFT": "Microsoft",
    "MU": "Micron Technology",
    "NSRGY": "Nestle",
    "NLLSY": "Nel ASA",
    "NFLX": "Netflix",
    "FLG": "New York Community Bancorp",
    "NKE": "Nike",
    "NIO": "Nio",
    "NVO": "Novo Nordisk",
    "NVDA": "Nvidia",
    "ORCL": "Oracle",
    "PYPL": "Paypal",
    "PLTR": "Palantir Technologies",
    "PEP": "PepsiCo",
    "PFE": "Pfizer",
    "PLUG": "Plug Power",
    "POAHF": "Porsche AG",
    "PG": "Procter & Gamble",
    "QCOM": "Qualcomm",
    "RGLXY": "RTL Group",
    "CRM": "Salesforce",
    "SAP": "SAP",
    "RYDAF": "Shell",
    "SNDL": "SNDL",
    "SBUX": "Starbucks",
    "SYIN": "SynBiotic SE",
    "TGT": "Target",
    "TCEHY": "Tencent Holdings",
    "TSLA": "Tesla",
    "TLRY": "Tilray Brands",
    "TONR": "Tonner Drones",
    "TM": "Toyota Motor Corporation",
    "TSM": "Taiwan Semiconductor Manufacturing Company",
    "UNH": "UnitedHealth Group",
    "UPS": "United Parcel Service",
    "U": "Unity Software",
    "VZ": "Verizon Communications",
    "SPCE": "Virgin Galactic",
    "V": "Visa",
    "VLKPF": "Volkswagen AG",
    "DIS": "Walt Disney Company",
    "WMT": "Walmart",
}
